config/routes.rb
TwitterResearch::Application.routes.draw do
  devise_for :users

  root(:to => 'searches#index')
  resources(:searches)
  resources(:categories)

  resources(:tweets) do
    resources(:notes)
  end

end

app/models/.#user.rb
rmcaleavy@coders.davincicoders.com.2259:1343002470

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible(:title)
  validates(:title, presence: true, uniqueness: true)
  has_and_belongs_to_many(:tweets)

  def self.with_title (title)
    where('LOWER(title)=?', title.downcase)
  end


  def title_match? (other)
    title.downcase == other.downcase
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible(:note_text)
  validates(:note_text, presence: true)
  belongs_to(:tweet)
  belongs_to(:user)


end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible(:twitter_user, :tweeted_text, :tweeted_at, :categories_as_string)
  #allows mass assignment. never put a foriegn key in here.
  #only what you want a user to be able to use



  validates(:twitter_user, :presence => true)
  validates(:tweeted_text, :presence => true)
  validates(:tweeted_at, :presence => true)

  scope(:with_notes, includes(:notes).order('notes.created_at desc'))


        belongs_to(:user)
        has_many(:notes, :dependent => :delete_all)
        has_and_belongs_to_many(:categories)

        def suggested_categories
          titles = Category.all.map(&:title).map(&:downcase)
          tweet = tweeted_text.gsub(/[^\w\s]/, ' ').downcase.split.sort
          (tweet & titles).map(&:capitalize).sort.join(', ')
        end

        ##############################################################
        # Returns comma separated string of the current category titles.
        def categories_as_string
          categories.map(&:title).sort.join(', ')

        end
        ###########################################################################
        # Given a comma separated string of category titles, reset the
        # categories for this tweet to the categories in the string.

        def categories_as_string= (new_categories)
          categories.clear
          new_categories.split(/\s*,\s*/).each do |title|
            cat = Category.where('LOWER(title) = ?', title.downcase).first
            categories << cat if !cat.nil?
          end
        end
      end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible(:email, :password, :password_confirmation, :remember_me)

  validates(:email,     :presence => true, :uniqueness => true)

  has_many(:tweets)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to(:html, :json, :js)
  before_filter(:authenticate_user!)

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # Show a list of all categories
  def index
    @categories = Category.order(:title).limit(50)
    respond_with(@categories)
  end

  # Show a single category with all tweets
  def show
    @category = Category.includes(:tweets).
      order('tweets.tweeted_at desc').find(params[:id])
    respond_with(@category)
  end

  # Show form for a new category
  def new
    @category = Category.new
    respond_with(@category)
  end

  # Save/create the new category with new params
  def create
    @category = Category.create(params[:category])
    # flash.notice = "Great, you've created a custom category!" if !@category.new_record?
    respond_with(@category, location: categories_url)
  end

  # Show a form to let users edit form submitted
  def edit
    @category = Category.find(params[:id])
    respond_with(@category)
  end

  # Update the category after the edit form is submitted
  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    respond_with(@category)
  end

  # Delete a category
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_with(@category)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_filter(:fetch_tweet)
  before_filter(:fetch_note, except:[:index, :new, :create])

  def index
    @notes = @tweet.notes.order('created_at desc')
    respond_with([@tweet, @notes], location: tweet_url(@tweet))
  end


  def show
    respond_with([@tweet, @note], location: tweet_url(@tweet))
  end


  def new
    @note = @tweet.notes.build
    respond_with([@tweet, @note])
  end


  def create
    @note = @tweet.notes.create(params[:note])
    respond_with([@tweet, @note], location: tweet_url(@tweet))
  end


  def edit
    respond_with([@tweet, @note])
  end


  def update
    @note.update_attributes(params[:note])
    respond_with([@tweet, @note])
  end


  def destroy
    @note.destroy
    respond_with([@tweet, @notes])

  end

  ##########################################################
  private

  def fetch_tweet_and_maybe_note
    @tweet = current_user.tweets.find(params[:tweet_id])
    @note = @tweet.notes.find(params[:id]) if params[:id]
     end

  #########################################################
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
  end

  def show
    search = SimpleTwitter::Search.new
    search.results_per_page = params[:rpp]
    search.language = params[:lang]
    @results = search.search(params[:q])
    flash.notice = "Search completed"
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    # current_user from Devise is associated with "tweets"
    @tweets = current_user.tweets.order('tweeted_at desc').limit(25)
    respond_with(@tweets)
  end

  def show
    @tweet = current_user.tweets.with_notes.find(params[:id])
    respond_with(@tweet)
  end

  def create
    @tweet = current_user.tweets.create(params[:tweet])
    respond_with(@tweet, :location => tweets_url)
  end

  def edit
    @tweet = current_user.tweets.find(params[:id])
    respond_with(@tweet)
  end

  def update
    @tweet = current_user.tweets.find(params[:id])
    @tweet.update_attributes(params[:tweet])
    respond_with(@tweet)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/categories/_category.html.erb
<li id="<%= dom_)id(c) %>">
      <span class="title">
        <%= link_to(category.title, category_url(category)) %>
      </span>

      <span class="edit">
        <%= link_to('Edit', category_url(category)) %>
      </span>

      <span class="delete">
        <%= link_to('Delete', category_url(category)
                    :method => :delete,
                    :remote => true,
                    :data => {:confirm => "Are you sure?'}) %>
      </span>
</li>

app/views/categories/_form.html.erb
<%= form_for(@category, remote: true) do |form| %>
  <fieldset>
    <legend>Category</legend>

    <div>
      <%= form.label(:title) %>
      <%= form.text_field(:title) %>
    </div>

    <div>
      <%= form.submit('Cancel',type: 'button', name: 'cancel') %>
      <%= form.submit %>
    </div>
  </fieldset>
<% end %>

app/views/categories/create.js.erb
$(function () {
 var html = "<%= j(render(partial: 'category', object; @category)) %>";
 $("#categories").append(html);
$("#form").hide();
});

app/views/categories/destroy.js.erb
$(function() {
S("#<%= dom_id(@category %>").fadeOut();
});

app/views/categories/edit.html.erb
<%= form_for(@tweet) do |form| %>

  <fieldset>

    <legend>Edit a Tweet's Categories</legend>
    <div>
      <%= form.label(:categories_as_string, 'Categories') %>
      <%= form.text_field(:categories_as_string) %>
    </div>

    <%= form.submit %>
  </fieldset>
  <% end %>

app/views/categories/index.html.erb
<h1>
  Categories
  (<%= link_to('New', new_category_url) %>)
</h1>

<ul id="categories">
  <% @categories.each do |c| %>
    <li>
      <span class="title">
        <%= link_to(c.title, category_url(c)) %>
      </span>

      <span class="edit">
        <%= link_to('Edit', edit_category_url(c)) %>
      </span>

      <span class="delete">
        <%= link_to('Delete', category_url(c),
                    :method  => :delete,
                    :confirm => 'Are you sure?') %>
      </span>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<%= render(partial: 'form') %>

app/views/categories/new.js.erb
$(function () {
  var html = "<%= j(render(partial: 'form')) %>";
  $("#form").html(html).show();

$("#form input[name='cancel']").click(function (){
$("#form").hide();
});

});

app/views/categories/show.html.erb
<h1>Tweets in <%= @category.title %></h1>

<ul>
  <%= render(partial: 'tweets/tweet', collection: @category.tweets) %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterResearch</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if user_signed_in? %>

      <nav>
        <ul>
          <li><%= link_to('Search', searches_url) %></li>
          <li><%= link_to('My Saved Tweets', tweets_url) %></li>
          <li><%= link_to('My Categories', categories_url) %></li>


          <li>
            <%= link_to('Log Out', destroy_user_session_url,
                        :method  => :delete,
                        :data => {:confirm => "Are you sure you want to log out?"}) %>
          </li>
        </ul>
      </nav>
    <% end %>

    <% if !flash.empty? %>
      <div>
        <p><%= flash.notice%></p>
        <p><%= flash.alert %></p>
      </div>
    <% end %>


    <div id = "content">
      <%= yield %>

    </div>

  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for([@tweet, @note]) do |form|%>
  <fieldset>
    <legend>Note</legend>

    <div>
      <%= form.label(:note_text)%>
      <%= form.text_area(:note_text)%>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </fieldset>
<% end %>

app/views/notes/_show.html.erb
<div>

<span class="time"><%= show.created_at%></span>
  <p> <%= show.note_text %></p>
  </div>

app/views/notes/edit.html.erb
<%= render(:partial => "form") %>

app/views/notes/new.html.erb
<%= render(:partial => "form") %>

app/views/searches/index.html.erb
<div class="form">
  <form action="/searches/1" method="get">



<br/>

<SELECT name="lang">
        <OPTION value="en">English</OPTION>
        <OPTION value="fr">French</OPTION>
        <OPTION value="es">Spanish</OPTION>
        <OPTION value="ru">Russian</OPTION>
</SELECT>

<br/>

 <label>Results Per Page?</label><br/>
  <input type="radio" name="rpp" value="5" /> 5<br />
  <input type="radio" name="rpp" value="10" />10<br />
  <input type="radio" name="rpp" value="20" />20<br />

  <label>Search Twitter</label>
<input type="text" name="q" id="q" value="Search Twitter"/>
<input type="submit" name="submit" value="submit"/><br/>




</form>
</div>

app/views/searches/show.html.erb
<body>

  <h1> You searched for <%= params[:q] %></h1>


  <div id=base>
    <ul>
      <% @results.each do |r| %>
        <li>
          <img src="<%=r.avatar%>"/>
          <%= r.user %> <em>said</em>  <%= r.text %>
          <% tweet = Tweet.new(:twitter_user => r.user,
                               :tweeted_text => r.text,
                               :tweeted_at   => r.time) %>


          <%= r.text %>
          <%= form_for(tweet) do | form | %>
            <%= form.hidden_field(:twitter_user) %>
            <%= form.hidden_field(:tweeted_text) %>
            <%= form.hidden_field(:tweeted_at) %>

            <%= form.submit('Save') %>
          <% end %>
        </li>
      <% end %>

    </ul>
  </div>
</body>

app/views/tweets/_tweet.html.erb
<li>
  <%= tweet.twitter_user %> said <%= tweet.tweeted_text %>
  <%= link_to('view', tweet_url(tweet)) %>
</li>

app/views/tweets/edit.html.erb
<%= form_for(@tweet) do |form| %>

  <fieldset>

    <legend>Edit a Tweet's Categories</legend>

    <div class="form">
      <%= form.label(:categories_as_string, 'Categories') %>
      <%= form.text_field(:categories_as_string) %>
    </div>

    <%= form.submit %>
  </fieldset>
<% end %>

<h2>Available Categories</h2>

<ul>
  <% Category.order(:title).each do |c| %>
    <li><%= c.title %></li>
  <% end %>
</ul>

app/views/tweets/index.html.erb
<ul>

<% @tweets.each do |tweet| %>
    <li>
      [ID: <%= tweet.id %>]
      <%= tweet.twitter_user %> said <%= tweet.tweeted_text %> time <%= tweet.tweeted_at%>
      <%= link_to('View', tweet_url(tweet))%>
    </li>
  <% end %>

  <%= render(partial: 'tweet', collection: @tweets) %>
</ul>

app/views/tweets/show.html.erb
<div class="tweet">
  <h2>Tweet Info:</h2>
  <span>
    On <%= @tweet.tweeted_at %>, <%= @tweet.twitter_user %> said:
  </span>

  <p><%= @tweet.tweeted_text %></p>
</div>

<div class="categories">
  <h2>Categories <%= link_to('Edit', edit_tweet_url(@tweet)) %></h2>

  <% if @tweet.categories.empty? %>
    <h2>This tweet isn't in any categories.</h2>
  <% else %>
    <p><%= @tweet.categories.map(&:title).to_sentence %></p>
  <% end %>
</div>

<div class="notes">
  <h2>My Notes:</h2>
  <span>
    <%= link_to('Create New Note', new_tweet_note_url(@tweet)) %>
  </span>

  <%= render(partial: 'notes/show', collection: @tweet.notes) %>
</div>

app/views/tweets/tweet.html.erb
<li>
  <%= tweet.twitter_user %> said <%= tweet.tweeted_text %>
  <%= link_to('View', tweet_url(tweet)) %>
</li>